ci:
  config:
    schema_version: 1
    trunk_branch: main
    cli_version: v0.5.0-rc.10
    state_token: ${{ secrets.CASCADE_STATE_TOKEN }}
    manifest_file: .github/manifest.yaml
    manifest_key: ci
    environments: [prod]
    triggers: [src/**]
    builds:
      - name: app
        workflow: .github/workflows/build-app.yaml
        triggers: []
    deploys:
      - name: app
        workflow: .github/workflows/deploy-app.yaml
        triggers: []
    rollback:
      repository_dispatch:
        types: [rollback-requested]
  state:
    prod:
      sha: 6363df90f335c07c7a61748a7c64c663351409fe
      version: v0.1.0-rc.1
      committed_at: "2026-06-26T18:22:24Z"
      committed_by: joshua-temple
      deploys:
        app:
          sha: 6363df90f335c07c7a61748a7c64c663351409fe
          deployed_at: "2026-06-26T18:22:24Z"
          deployed_by: joshua-temple
